// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Intent.Modules.Java.ModelMapper.Templates.EntityToDtoMapping
{
    using System.Collections.Generic;
    using System.Linq;
    using Intent.Modules.Common;
    using Intent.Modules.Common.Templates;
    using Intent.Modules.Common.Java.Templates;
    using Intent.Templates;
    using Intent.Metadata.Models;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Dev\Intent.Modules.Java\Intent.Modules.Java.ModelMapper\Templates\EntityToDtoMapping\EntityToDtoMappingTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class EntityToDtoMappingTemplate : JavaTemplateBase<Intent.Modelers.Services.Api.DTOModel>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("package ");
            
            #line 10 "C:\Dev\Intent.Modules.Java\Intent.Modules.Java.ModelMapper\Templates\EntityToDtoMapping\EntityToDtoMappingTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Package));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\nimport org.modelmapper.PropertyMap;\r\n\r\npublic class ");
            
            #line 14 "C:\Dev\Intent.Modules.Java\Intent.Modules.Java.ModelMapper\Templates\EntityToDtoMapping\EntityToDtoMappingTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(" extends PropertyMap<");
            
            #line 14 "C:\Dev\Intent.Modules.Java\Intent.Modules.Java.ModelMapper\Templates\EntityToDtoMapping\EntityToDtoMappingTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetTypeName(_entity.InternalElement)));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 14 "C:\Dev\Intent.Modules.Java\Intent.Modules.Java.ModelMapper\Templates\EntityToDtoMapping\EntityToDtoMappingTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetDtoType()));
            
            #line default
            #line hidden
            this.Write("> {\r\n    protected void configure() {\r\n");
            
            #line 16 "C:\Dev\Intent.Modules.Java\Intent.Modules.Java.ModelMapper\Templates\EntityToDtoMapping\EntityToDtoMappingTemplate.tt"
  foreach(var mapping in GetMappings()) { 
            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 17 "C:\Dev\Intent.Modules.Java\Intent.Modules.Java.ModelMapper\Templates\EntityToDtoMapping\EntityToDtoMappingTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mapping));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 18 "C:\Dev\Intent.Modules.Java\Intent.Modules.Java.ModelMapper\Templates\EntityToDtoMapping\EntityToDtoMappingTemplate.tt"
  } 
            
            #line default
            #line hidden
            this.Write("    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
