// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Intent.Modules.Java.Spring.Data.Repositories.Templates.EntityRepository
{
    using System.Collections.Generic;
    using System.Linq;
    using Intent.Modules.Common;
    using Intent.Modules.Common.Templates;
    using Intent.Modules.Common.Java.Templates;
    using Intent.Templates;
    using Intent.Metadata.Models;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Dev\Intent.Modules.Java\Intent.Modules.Java.Spring.Data.Repositories\Templates\EntityRepository\EntityRepositoryTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class EntityRepositoryTemplate : JavaTemplateBase<Intent.Modelers.Domain.Api.ClassModel, Intent.Modules.Java.Spring.Data.Repositories.Templates.EntityRepository.EntityRepositoryDecorator>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("package ");
            
            #line 10 "C:\Dev\Intent.Modules.Java\Intent.Modules.Java.Spring.Data.Repositories\Templates\EntityRepository\EntityRepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Package));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\nimport org.springframework.data.jpa.repository.JpaRepository;\r\n\r\n/**\r\n * Spr" +
                    "ing Data JPA repository for the ");
            
            #line 15 "C:\Dev\Intent.Modules.Java\Intent.Modules.Java.Spring.Data.Repositories\Templates\EntityRepository\EntityRepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetEntityType()));
            
            #line default
            #line hidden
            this.Write(" entity.\r\n */\r\n");
            
            #line 17 "C:\Dev\Intent.Modules.Java\Intent.Modules.Java.Spring.Data.Repositories\Templates\EntityRepository\EntityRepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.IntentIgnoreBodyAnnotation()));
            
            #line default
            #line hidden
            this.Write("\r\npublic interface ");
            
            #line 18 "C:\Dev\Intent.Modules.Java\Intent.Modules.Java.Spring.Data.Repositories\Templates\EntityRepository\EntityRepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(" extends JpaRepository<");
            
            #line 18 "C:\Dev\Intent.Modules.Java\Intent.Modules.Java.Spring.Data.Repositories\Templates\EntityRepository\EntityRepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetEntityType()));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 18 "C:\Dev\Intent.Modules.Java\Intent.Modules.Java.Spring.Data.Repositories\Templates\EntityRepository\EntityRepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetEntityIdType()));
            
            #line default
            #line hidden
            this.Write("> {\r\n");
            
            #line 19 "C:\Dev\Intent.Modules.Java\Intent.Modules.Java.Spring.Data.Repositories\Templates\EntityRepository\EntityRepositoryTemplate.tt"
  foreach(var query in GetQueriesFromIndexes()) { 
            
            #line default
            #line hidden
            this.Write("    ");
            
            #line 20 "C:\Dev\Intent.Modules.Java\Intent.Modules.Java.Spring.Data.Repositories\Templates\EntityRepository\EntityRepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(query));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            
            #line 22 "C:\Dev\Intent.Modules.Java\Intent.Modules.Java.Spring.Data.Repositories\Templates\EntityRepository\EntityRepositoryTemplate.tt"
  } 
            
            #line default
            #line hidden
            
            #line 23 "C:\Dev\Intent.Modules.Java\Intent.Modules.Java.Spring.Data.Repositories\Templates\EntityRepository\EntityRepositoryTemplate.tt"
  foreach(var member in GetDecorators().SelectMany(x => x.GetMembers())) { 
            
            #line default
            #line hidden
            this.Write("    ");
            
            #line 24 "C:\Dev\Intent.Modules.Java\Intent.Modules.Java.Spring.Data.Repositories\Templates\EntityRepository\EntityRepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            
            #line 26 "C:\Dev\Intent.Modules.Java\Intent.Modules.Java.Spring.Data.Repositories\Templates\EntityRepository\EntityRepositoryTemplate.tt"
  } 
            
            #line default
            #line hidden
            this.Write("}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
