// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Intent.Modules.Java.SpringFox.Swagger.Templates.SpringFoxConfig
{
    using System.Collections.Generic;
    using System.Linq;
    using Intent.Modules.Common;
    using Intent.Modules.Common.Templates;
    using Intent.Modules.Common.Java.Templates;
    using Intent.Templates;
    using Intent.Metadata.Models;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Dev\Intent.Modules.Java\Intent.Modules.Java.SpringFox.Swagger\Templates\SpringFoxConfig\SpringFoxConfigTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class SpringFoxConfigTemplate : JavaTemplateBase<object>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("package ");
            
            #line 10 "C:\Dev\Intent.Modules.Java\Intent.Modules.Java.SpringFox.Swagger\Templates\SpringFoxConfig\SpringFoxConfigTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Package));
            
            #line default
            #line hidden
            this.Write(@";

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.web.servlet.config.annotation.EnableWebMvc;

import springfox.documentation.builders.PathSelectors;
import springfox.documentation.builders.RequestHandlerSelectors;
import springfox.documentation.spi.DocumentationType;
import springfox.documentation.spring.web.plugins.Docket;

@Configuration
@EnableWebMvc
public class ");
            
            #line 23 "C:\Dev\Intent.Modules.Java\Intent.Modules.Java.SpringFox.Swagger\Templates\SpringFoxConfig\SpringFoxConfigTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(" {\r\n\r\n    @Bean\r\n    public Docket api() {\r\n        return new Docket(Documentati" +
                    "onType.SWAGGER_2)\r\n");
            
            #line 28 "C:\Dev\Intent.Modules.Java\Intent.Modules.Java.SpringFox.Swagger\Templates\SpringFoxConfig\SpringFoxConfigTemplate.tt"
 if (_usesJwtAuth) { 
            
            #line default
            #line hidden
            this.Write("          .securityContexts(");
            
            #line 29 "C:\Dev\Intent.Modules.Java\Intent.Modules.Java.SpringFox.Swagger\Templates\SpringFoxConfig\SpringFoxConfigTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ImportType("java.util.Arrays")));
            
            #line default
            #line hidden
            this.Write(".asList(securityContext()))\r\n          .securitySchemes(Arrays.asList(apiKey()))\r" +
                    "\n");
            
            #line 31 "C:\Dev\Intent.Modules.Java\Intent.Modules.Java.SpringFox.Swagger\Templates\SpringFoxConfig\SpringFoxConfigTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("          .select()\r\n          .apis(RequestHandlerSelectors.any())\r\n          .p" +
                    "aths(PathSelectors.any())\r\n          .build();\r\n    }\r\n");
            
            #line 37 "C:\Dev\Intent.Modules.Java\Intent.Modules.Java.SpringFox.Swagger\Templates\SpringFoxConfig\SpringFoxConfigTemplate.tt"
 if (_usesJwtAuth) { 
            
            #line default
            #line hidden
            this.Write("\r\n    private ");
            
            #line 39 "C:\Dev\Intent.Modules.Java\Intent.Modules.Java.SpringFox.Swagger\Templates\SpringFoxConfig\SpringFoxConfigTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ImportType("springfox.documentation.spi.service.contexts.SecurityContext")));
            
            #line default
            #line hidden
            this.Write(" securityContext() {\r\n        return SecurityContext.builder().securityReferences" +
                    "(defaultAuth()).build();\r\n    }\r\n\r\n    private ");
            
            #line 43 "C:\Dev\Intent.Modules.Java\Intent.Modules.Java.SpringFox.Swagger\Templates\SpringFoxConfig\SpringFoxConfigTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ImportType("java.util.List")));
            
            #line default
            #line hidden
            this.Write("<");
            
            #line 43 "C:\Dev\Intent.Modules.Java\Intent.Modules.Java.SpringFox.Swagger\Templates\SpringFoxConfig\SpringFoxConfigTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ImportType("springfox.documentation.service.SecurityReference")));
            
            #line default
            #line hidden
            this.Write("> defaultAuth() {\r\n        ");
            
            #line 44 "C:\Dev\Intent.Modules.Java\Intent.Modules.Java.SpringFox.Swagger\Templates\SpringFoxConfig\SpringFoxConfigTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ImportType("springfox.documentation.service.AuthorizationScope")));
            
            #line default
            #line hidden
            this.Write(@" authorizationScope = new AuthorizationScope(""global"", ""accessEverything"");
        AuthorizationScope[] authorizationScopes = new AuthorizationScope[1];
        authorizationScopes[0] = authorizationScope;
        return Arrays.asList(new SecurityReference(""JWT"", authorizationScopes));
    }

    private ");
            
            #line 50 "C:\Dev\Intent.Modules.Java\Intent.Modules.Java.SpringFox.Swagger\Templates\SpringFoxConfig\SpringFoxConfigTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ImportType("springfox.documentation.service.ApiKey")));
            
            #line default
            #line hidden
            this.Write(" apiKey() {\r\n        return new ApiKey(\"JWT\", \"Authorization\", \"header\");\r\n    }\r" +
                    "\n");
            
            #line 53 "C:\Dev\Intent.Modules.Java\Intent.Modules.Java.SpringFox.Swagger\Templates\SpringFoxConfig\SpringFoxConfigTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
