// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Intent.Modules.Java.Domain.Templates.AbstractEntity
{
    using System.Collections.Generic;
    using System.Linq;
    using Intent.Modules.Common;
    using Intent.Modules.Common.Templates;
    using Intent.Modules.Common.Java.Templates;
    using Intent.Templates;
    using Intent.Metadata.Models;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Dev\Intent.Modules.Java\Intent.Modules.Java.Domain\Templates\AbstractEntity\AbstractEntityTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class AbstractEntityTemplate : JavaTemplateBase<object, Intent.Modules.Java.Domain.Templates.AbstractEntity.AbstractEntityDecorator>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\npackage ");
            
            #line 11 "C:\Dev\Intent.Modules.Java\Intent.Modules.Java.Domain\Templates\AbstractEntity\AbstractEntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Package));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\nimport java.io.Serializable;\r\n\r\n");
            
            #line 15 "C:\Dev\Intent.Modules.Java\Intent.Modules.Java.Domain\Templates\AbstractEntity\AbstractEntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetClassAnnotations()));
            
            #line default
            #line hidden
            this.Write("\r\npublic abstract class ");
            
            #line 16 "C:\Dev\Intent.Modules.Java\Intent.Modules.Java.Domain\Templates\AbstractEntity\AbstractEntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(" implements Serializable {\r\n    private static final long serialVersionUID = 1L;");
            
            #line 17 "C:\Dev\Intent.Modules.Java\Intent.Modules.Java.Domain\Templates\AbstractEntity\AbstractEntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetFields()));
            
            #line default
            #line hidden
            
            #line 17 "C:\Dev\Intent.Modules.Java\Intent.Modules.Java.Domain\Templates\AbstractEntity\AbstractEntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetMethods()));
            
            #line default
            #line hidden
            this.Write("\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
