// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Intent.Modules.Java.SpringBoot.Templates.IntentAnnotations
{
    using System.Collections.Generic;
    using System.Linq;
    using Intent.Modules.Common;
    using Intent.Modules.Common.Templates;
    using Intent.Modules.Common.Java.Templates;
    using Intent.Templates;
    using Intent.Metadata.Models;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Dev\Intent.Modules.Java\Intent.Modules.Java.SpringBoot\Templates\IntentAnnotations\IntentAnnotationsTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class IntentAnnotationsTemplate : JavaTemplateBase<object>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write(@"import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;
 
@Target(ElementType.CLASS, ElementType.METHOD, ElementType.FIELD)
@Retention(RetentionPolicy.SOURCE)
public @interface IntentIgnore{
}

@Target(ElementType.CLASS, ElementType.METHOD, ElementType.FIELD)
@Retention(RetentionPolicy.SOURCE)
public @interface IntentIgnoreBody{
}

@Target(ElementType.CLASS, ElementType.METHOD, ElementType.FIELD)
@Retention(RetentionPolicy.SOURCE)
public @interface IntentMerge{
}

@Target(ElementType.CLASS, ElementType.METHOD, ElementType.FIELD)
@Retention(RetentionPolicy.SOURCE)
public @interface IntentManage{
}

@Target(ElementType.CLASS, ElementType.METHOD, ElementType.FIELD)
@Retention(RetentionPolicy.SOURCE)
public @interface IntentCanAdd{
}

@Target(ElementType.CLASS, ElementType.METHOD, ElementType.FIELD)
@Retention(RetentionPolicy.SOURCE)
public @interface IntentCanUpdate{
}

@Target(ElementType.CLASS, ElementType.METHOD, ElementType.FIELD)
@Retention(RetentionPolicy.SOURCE)
public @interface IntentCanRemove{
}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
