//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:6.0.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intent.Modules.Java.Services.Templates.ServiceInterface {
    using System.Collections.Generic;
    using System.Linq;
    using Intent.Modules.Common;
    using Intent.Modules.Common.Templates;
    using Intent.Modules.Common.Java.Templates;
    using Intent.Templates;
    using Intent.Metadata.Models;
    using Intent.Modelers.Services.Api;
    using System;
    
    
    public partial class ServiceInterfaceTemplate : JavaTemplateBase<Intent.Modelers.Services.Api.ServiceModel, Intent.Modules.Java.Services.Templates.ServiceInterface.ServiceInterfaceDecorator> {
        
        public override string TransformText() {
            this.GenerationEnvironment = null;
            
            #line 11 ""
            this.Write("package ");
            
            #line default
            #line hidden
            
            #line 11 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( Package ));
            
            #line default
            #line hidden
            
            #line 11 ""
            this.Write(";\r\n\r\npublic interface ");
            
            #line default
            #line hidden
            
            #line 13 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( ClassName ));
            
            #line default
            #line hidden
            
            #line 13 ""
            this.Write(" {\r\n");
            
            #line default
            #line hidden
            
            #line 14 ""
  foreach(var operation in Model.Operations) { 
            
            #line default
            #line hidden
            
            #line 15 ""
            this.Write("    ");
            
            #line default
            #line hidden
            
            #line 15 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( GetTypeName(operation) ));
            
            #line default
            #line hidden
            
            #line 15 ""
            this.Write(" ");
            
            #line default
            #line hidden
            
            #line 15 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( operation.Name ));
            
            #line default
            #line hidden
            
            #line 15 ""
            this.Write("(");
            
            #line default
            #line hidden
            
            #line 15 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( this.GetMethodParameters(operation.Parameters) ));
            
            #line default
            #line hidden
            
            #line 15 ""
            this.Write(")");
            
            #line default
            #line hidden
            
            #line 15 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( GetCheckedExceptions(operation) ));
            
            #line default
            #line hidden
            
            #line 15 ""
            this.Write(";\r\n\r\n");
            
            #line default
            #line hidden
            
            #line 17 ""
  } 
            
            #line default
            #line hidden
            
            #line 18 ""
            this.Write("}");
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        public override void Initialize() {
            base.Initialize();
        }
    }
}
